<a href="https://colab.research.google.com/github/ThaikoZ/data-science/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteka **NUMPY**

In [3]:
import numpy as np

np.__version__

'1.23.5'

In [ ]:
print(dir(np)) # Wyświetla możliwe metody numpy

In [ ]:
help(np.array) # Wyświetla szczegóły dotyczące konkretnej metody



---



## Podstawowe atrybuty tablic

**ndim** - zwraca numer wymiarów - Number of Dimensions

**shape** - zwraca rozmiar każdego wymiaru

**size** - ilość elementów w tablicy

**dtype** - zwraca typ danych tablicy np. *int8, int32, int64, float, bool, complex*

In [14]:
x = np.array([[2, 3, 2], [1, 4, 3]])
print(x)

[[2 3 2]
 [1 4 3]]


In [15]:
x.ndim # Zwraca numer wymiarów - Number of Dimensions

2

In [16]:
x.shape # Zwraca rozmiar każdego wymiaru

(2, 3)

In [17]:
x.size # Ilość elementów w tablicy

6

In [18]:
x.dtype # Zwraca typ danych tablicy

dtype('int64')



---


## Tworzenie tablic

Każda przyjmuje również następujące parametry (*dtype=float, order='C', like=None*) z wyjątkiem linspace

**np.zeros(** *shape* **)** - wypełnia tablicę zerami

**np.ones(** *shape* **)** - wypełnia tablicę jedynkami

**np.full(** *shape, fill_value* **)** - wypełnia tablicę fill_value

**np.arange(** *start, stop, step* **)** - wypełnia tablicę range()

**np.linspace(** *start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0* **)** - dostajemy równo rozłożone elementy


**reshape((3, 2))** - zwraca tablicę w strukturze 3, 2

In [21]:
x = np.zeros(shape=(4, 10), dtype='int')
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [24]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.full(shape=(4, 4), fill_value=4, dtype='int')

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [39]:
A = np.arange(start=1, stop=16, step=1 )
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
np.linspace(start=10, stop = 50, num=70)

array([10.        , 10.57971014, 11.15942029, 11.73913043, 12.31884058,
       12.89855072, 13.47826087, 14.05797101, 14.63768116, 15.2173913 ,
       15.79710145, 16.37681159, 16.95652174, 17.53623188, 18.11594203,
       18.69565217, 19.27536232, 19.85507246, 20.43478261, 21.01449275,
       21.5942029 , 22.17391304, 22.75362319, 23.33333333, 23.91304348,
       24.49275362, 25.07246377, 25.65217391, 26.23188406, 26.8115942 ,
       27.39130435, 27.97101449, 28.55072464, 29.13043478, 29.71014493,
       30.28985507, 30.86956522, 31.44927536, 32.02898551, 32.60869565,
       33.1884058 , 33.76811594, 34.34782609, 34.92753623, 35.50724638,
       36.08695652, 36.66666667, 37.24637681, 37.82608696, 38.4057971 ,
       38.98550725, 39.56521739, 40.14492754, 40.72463768, 41.30434783,
       41.88405797, 42.46376812, 43.04347826, 43.62318841, 44.20289855,
       44.7826087 , 45.36231884, 45.94202899, 46.52173913, 47.10144928,
       47.68115942, 48.26086957, 48.84057971, 49.42028986, 50.  

In [40]:
A.reshape((3, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [43]:
A.reshape((-1, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])



---

## Podstawowe działania na tablicach

* A+B lub **add**(A, B)
* A-B lub **substract**(A, B)
* A\*B lub **multiply**(A, B)
* A/B lub **divide**(A, B)
* A+3
* A-7
* B/2
* np.dot(A, B), X.dot(B), A @ B

In [50]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

print(A+B, A-B, A*B, A/B)

[6 0 7 4] [0 2 1 0] [ 9 -1 12  4] [ 1.         -1.          1.33333333  1.        ]


In [53]:
print(A+5, B-2, A*6, B/2 )

[8 6 9 7] [ 1 -3  1  0] [18  6 24 12] [ 1.5 -0.5  1.5  1. ]


In [60]:
A = A.reshape((2, 2))
B = B.reshape((2, 2))

array([[12, -1],
       [18,  0]])

In [61]:
np.dot(A, B)

array([[12, -1],
       [18,  0]])

In [63]:
A @ B

array([[12, -1],
       [18,  0]])

In [64]:
A.dot(B)

array([[12, -1],
       [18,  0]])



---

## Generowanie liczb pseudolosowych


In [74]:
np.random.seed(0)

In [79]:
np.random.randn()

1.8675579901499675

In [82]:
np.random.randn(4,4 )

array([[ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628],
       [-1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
       [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056]])

In [84]:
np.random.rand(3 ,3 ,3 )

array([[[0.66741038, 0.13179786, 0.7163272 ],
        [0.28940609, 0.18319136, 0.58651293],
        [0.02010755, 0.82894003, 0.00469548]],

       [[0.67781654, 0.27000797, 0.73519402],
        [0.96218855, 0.24875314, 0.57615733],
        [0.59204193, 0.57225191, 0.22308163]],

       [[0.95274901, 0.44712538, 0.84640867],
        [0.69947928, 0.29743695, 0.81379782],
        [0.39650574, 0.8811032 , 0.58127287]]])

In [91]:
np.random.randint(15)

13

In [92]:
np.random.randint(low=10, high=101, size=10)

array([93, 43, 42, 80, 95, 41, 23, 81, 66, 34])

In [97]:
np.random.choice([2, 3, 4, 7, 1])

3